### ISSUE TITLE
Hives can be built on Marine side if more than one Tech Point exists

### ISSUE THREAD

**Issue by DalinSeivewright** [TheRealNin/SiegePlusPlus#9]
Hives can be dropped, for example in trimsiege, on MS techpoints.  IMO, the Comm should definitely not have to lock these down until at least front door opens (maybe never if he chooses not to.)

A couple of solutions:
* Make Hives killable by the FuncMaid entity like Cysts are.  Either if it's the Front Door Maid, Siege Door Maid, Both (or we add a new type).
** This will prevent them from dropping Hives in MS, assuming a mapper were to place one at MS (current and future maps would need to add one if multiple Tech Points exist) until the relevant timer expires.

* Make Tech Points marked for CCs not allow you drop Hives at all.
** This will prevent the rare occurrence of base switching... while this is extremely fun when it happens, it isn't entirely needed.

**Comment by TheRealNin** [comment]
How about just allowing damage to hives and command chairs during pregame?

**Comment by DalinSeivewright** [comment]
IMO then that distracts the marines from focusing on building up their defense either by pulling marines from the front or by forcing arc deployment.  I dont think the Aliens should be able to affect pre-game in the slightest.  If the comm also makes even the slightest tactical error the result may mean not being able to drop ccs at all.  Meanwhile Aliens would be swimming in hive-placement res.

**Comment by DalinSeivewright** [comment]
But actually....  Youre right in that rines could technically do thia to the aliens as well, although it would impact rines waaayyyy more.  So I say we prevent placement on either sides tech points.

**Comment by TheRealNin** [comment]
Hives start with almost no HP though. It's easy enough for a single marine to hit it with their rifle...

**Comment by cryticx** [comment]
So we'll just make hives killable? We all gonna agree on that?

**Comment by DalinSeivewright** [comment]
I consider this more of a bug than anything so i don't think it necessarily needs to be put in a "bill" (side note..  we should call them change sets or something) that is approved by everyone so I agree that we can move forward and allow damage for the hives and CC to mitigate that issue.  I'll see how that goes and if I really want a different solution I can bring it on Discord later.
